export const foodData = [
  {
    ratings: "4.4 - 30mins",
    image: "/foodScroll/food1.jpg",
    title: "McDonald's",
    items: "Smoothies, Bistro, Pastries",
    city: "Perungulathur",
    url: "mcdonalds",
    listItems: [
      { itemName: "McFlurry", itemPrice: "$2.99" },
      { itemName: "Big Mac", itemPrice: "$5.99" },
      { itemName: "McNuggets", itemPrice: "$4.99" },
      { itemName: "Filet-O-Fish", itemPrice: "$6.49" },
      { itemName: "Happy Meal", itemPrice: "$3.99" },
      { itemName: "Apple Pie", itemPrice: "$1.49" },
      { itemName: "Fries", itemPrice: "$2.49" },
      { itemName: "Egg McMuffin", itemPrice: "$4.49" },
      { itemName: "Sausage McMuffin", itemPrice: "$3.99" },
      { itemName: "Mocha Frappé", itemPrice: "$4.99" },
    ],
  },
  {
    ratings: "4.7 - 35mins",
    image: "/foodScroll/food2.jpg",
    title: "Subway's",
    items: "Fresh Juices, Coffee Shop, Ice Cream",
    city: "Mumbai",
    url: "subways",
    listItems: [
      { itemName: "Caramel Macchiato", itemPrice: "$4.99" },
      { itemName: "Iced Americano", itemPrice: "$3.99" },
      { itemName: "Cappuccino", itemPrice: "$4.49" },
      { itemName: "Mocha Frappuccino", itemPrice: "$5.49" },
      { itemName: "Croissant", itemPrice: "$2.99" },
      { itemName: "Blueberry Muffin", itemPrice: "$3.49" },
      { itemName: "Cinnamon Roll", itemPrice: "$3.99" },
      { itemName: "Chocolate Donut", itemPrice: "$2.49" },
      { itemName: "Cheese Danish", itemPrice: "$3.49" },
      { itemName: "Pumpkin Spice Latte", itemPrice: "$5.99" },
    ],
  },
  {
    ratings: "4.9 - 40mins",
    image: "/foodScroll/food3.jpg",
    title: "The Red Box",
    items: "Mocktails, Tea House, Cupcakes",
    city: "New York",
    url: "theredbox",
    listItems: [
      { itemName: "Red Velvet Cupcake", itemPrice: "$3.99" },
      { itemName: "Masala Chai", itemPrice: "$2.49" },
      { itemName: "Blue Lagoon Mocktail", itemPrice: "$4.99" },
      { itemName: "Lemon Infusion", itemPrice: "$3.49" },
      { itemName: "Green Tea Cupcake", itemPrice: "$4.29" },
      { itemName: "Mint Mojito", itemPrice: "$4.79" },
      { itemName: "Earl Grey Delight", itemPrice: "$3.99" },
      { itemName: "Vanilla Chai Latte", itemPrice: "$4.49" },
      { itemName: "Strawberry Bliss Mocktail", itemPrice: "$5.29" },
      { itemName: "Chocolate Truffle Cupcake", itemPrice: "$4.99" },
    ],
  },
  {
    ratings: "4.4 - 20mins",
    image: "/foodScroll/food4.jpg",
    title: "KFC",
    items: "Milkshakes, Espresso Bar, Gelato",
    city: "Tokyo",
    url: "kfc",
    listItems: [
      { itemName: "Classic Chocolate Milkshake", itemPrice: "$3.99" },
      { itemName: "Espresso Shot", itemPrice: "$2.49" },
      { itemName: "Strawberry Gelato", itemPrice: "$4.99" },
      { itemName: "Vanilla Latte", itemPrice: "$3.49" },
      { itemName: "Cookies and Cream Milkshake", itemPrice: "$4.29" },
      { itemName: "Caramel Macchiato", itemPrice: "$4.79" },
      { itemName: "Pistachio Gelato", itemPrice: "$3.99" },
      { itemName: "Iced Mocha", itemPrice: "$4.49" },
      { itemName: "Mint Chocolate Chip Gelato", itemPrice: "$5.29" },
      { itemName: "Hazelnut Latte", itemPrice: "$4.99" },
    ],
  },
  {
    ratings: "4.0 - 25mins",
    image: "/foodScroll/food5.jpg",
    title: "Faasos-Wraps, Rolls",
    items: "Salads, French Bakery, Puddings",
    city: "London",
    url: "faasos",
    listItems: [
      { itemName: "Chicken Tikka Wrap", itemPrice: "$7.99" },
      { itemName: "Paneer Roll", itemPrice: "$6.99" },
      { itemName: "Caesar Salad", itemPrice: "$5.99" },
      { itemName: "Chocolate Eclair", itemPrice: "$3.49" },
      { itemName: "Veggie Wrap", itemPrice: "$6.49" },
      { itemName: "Blueberry Muffin", itemPrice: "$2.99" },
      { itemName: "Greek Salad", itemPrice: "$7.49" },
      { itemName: "Fruit Pudding", itemPrice: "$4.99" },
      { itemName: "Chicken Shawarma Roll", itemPrice: "$8.49" },
      { itemName: "Creme Brulee", itemPrice: "$5.29" },
    ],
  },
  {
    ratings: "4.8 - 30mins",
    image: "/foodScroll/food6.jpg",
    title: "Behrouz Biriyani",
    items: "BBQ, Craft Cocktails, Donuts",
    city: "Sydney",
    url: "behrouzbiriyani",
    listItems: [
      { itemName: "Saffron Chicken Biryani", itemPrice: "$11.99" },
      { itemName: "Mutton Dum Biryani", itemPrice: "$13.99" },
      { itemName: "Veg Seekh Kebab", itemPrice: "$8.99" },
      { itemName: "Rose Falooda", itemPrice: "$5.49" },
      { itemName: "Paneer Tikka", itemPrice: "$9.49" },
      { itemName: "Craft Beer", itemPrice: "$6.99" },
      { itemName: "Gulab Jamun", itemPrice: "$3.99" },
      { itemName: "BBQ Chicken Wings", itemPrice: "$7.99" },
      { itemName: "Chocolate Donut", itemPrice: "$2.49" },
      { itemName: "Kesar Pista Lassi", itemPrice: "$4.49" },
    ],
  },
  {
    ratings: "4.4 - 32mins",
    image: "/foodScroll/food7.jpg",
    title: "Lunch Box - Meals and Thalis",
    items: "Pasta, Tea Lounge, Sorbet",
    city: "Paris",
    url: "lunchbox",
    listItems: [
      { itemName: "Spaghetti Bolognese", itemPrice: "$10.99" },
      { itemName: "Green Tea", itemPrice: "$2.99" },
      { itemName: "Ravioli with Pesto Sauce", itemPrice: "$12.49" },
      { itemName: "Assorted Thali", itemPrice: "$15.99" },
      { itemName: "Fruit Sorbet", itemPrice: "$6.49" },
      { itemName: "Herbal Infusion", itemPrice: "$4.99" },
      { itemName: "Lemon Sorbet", itemPrice: "$5.99" },
      { itemName: "Chicken Alfredo Pasta", itemPrice: "$11.49" },
      { itemName: "Masala Chai", itemPrice: "$3.49" },
      { itemName: "Chocolate Mousse", itemPrice: "$7.99" },
    ],
  },
  {
    ratings: "4.7 - 20mins",
    image: "/foodScroll/food8.jpg",
    title: "The Good Bowl",
    items: "Wraps, Lemonades, Cheesecakes",
    city: "Dubai",
    url: "thegoodbowl",
    listItems: [
      { itemName: "Chicken Shawarma Wrap", itemPrice: "$8.99" },
      { itemName: "Mint Lemonade", itemPrice: "$3.49" },
      { itemName: "Vegetarian Quinoa Bowl", itemPrice: "$10.49" },
      { itemName: "Classic Cheesecake", itemPrice: "$5.99" },
      { itemName: "Falafel Wrap", itemPrice: "$7.49" },
      { itemName: "Strawberry Lemonade", itemPrice: "$3.99" },
      { itemName: "Pesto Chicken Pasta", itemPrice: "$11.99" },
      { itemName: "Oreo Cheesecake", itemPrice: "$6.49" },
      { itemName: "Beef Burrito", itemPrice: "$9.99" },
      { itemName: "Blueberry Lemonade", itemPrice: "$4.49" },
    ],
  },
  {
    ratings: "4.8 - 20mins",
    image: "/foodScroll/food9.jpg",
    title: "EatFit",
    items: "Seafood, Fresh Squeezed Juices",
    city: "Rio de Janeiro",
    url: "eatfit",
    listItems: [
      { itemName: "Grilled Salmon", itemPrice: "$12.99" },
      { itemName: "Mango Tango Juice", itemPrice: "$4.49" },
      { itemName: "Quinoa Salad", itemPrice: "$9.99" },
      { itemName: "Shrimp Stir-Fry", itemPrice: "$11.49" },
      { itemName: "Detox Green Juice", itemPrice: "$5.99" },
      { itemName: "Chicken Caesar Wrap", itemPrice: "$8.99" },
      { itemName: "Fish Tacos", itemPrice: "$10.99" },
      { itemName: "Watermelon Splash", itemPrice: "$3.99" },
      { itemName: "Avocado Toast", itemPrice: "$6.49" },
      { itemName: "Pineapple Mint Smoothie", itemPrice: "$4.99" },
    ],
  },
  {
    ratings: "4.9 - 20mins",
    image: "/foodScroll/food10.jpg",
    title: "Haggen Dazs",
    items: "Mexican Cuisine, Herbal Infusions",
    city: "Cape Town",
    url: "haggendazs",
    listItems: [
      { itemName: "Taco Supreme", itemPrice: "$8.99" },
      { itemName: "Guacamole and Chips", itemPrice: "$5.49" },
      { itemName: "Enchiladas Verdes", itemPrice: "$10.99" },
      { itemName: "Herbal Infusion Tea", itemPrice: "$3.99" },
      { itemName: "Quesadilla with Salsa", itemPrice: "$7.99" },
      { itemName: "Churros with Chocolate Sauce", itemPrice: "$4.99" },
      { itemName: "Mexican Street Corn", itemPrice: "$6.49" },
      { itemName: "Horchata Drink", itemPrice: "$3.49" },
      { itemName: "Herb-Infused Ice Cream", itemPrice: "$6.99" },
      { itemName: "Sopapillas", itemPrice: "$4.49" },
    ],
  },
];

export const offerData = [
  {
    ratings: "4.2 - 25mins",
    image: "/offers/offer1.jpg",
    title: "Pizza Hut",
    url: "pizzahut",
    items: "Special Combo Deal",
    city: "Berlin",
    listItems: [
      { itemName: "Margherita Pizza", itemPrice: "$10.99" },
      { itemName: "Pepperoni Pasta", itemPrice: "$8.99" },
      { itemName: "Garlic Bread", itemPrice: "$4.49" },
      { itemName: "Soft Drink", itemPrice: "$1.99" },
      { itemName: "Chocolate Brownie", itemPrice: "$3.99" },
      { itemName: "Salad", itemPrice: "$5.99" },
      { itemName: "Chicken Wings", itemPrice: "$7.99" },
      { itemName: "Cheese Sticks", itemPrice: "$6.49" },
      { itemName: "Tiramisu", itemPrice: "$4.99" },
      { itemName: "Ice Cream", itemPrice: "$3.49" },
    ],
  },
  {
    ratings: "4.5 - 30mins",
    image: "/offers/offer2.jpg",
    title: "Starbucks",
    url: "startbucks",
    items: "Buy 1 Get 1 Free on Coffee",
    city: "Los Angeles",
    listItems: [
      { itemName: "Caramel Macchiato", itemPrice: "$4.99" },
      { itemName: "Iced Americano", itemPrice: "$3.99" },
      { itemName: "Cappuccino", itemPrice: "$4.49" },
      { itemName: "Mocha Frappuccino", itemPrice: "$5.49" },
      { itemName: "Croissant", itemPrice: "$2.99" },
      { itemName: "Blueberry Muffin", itemPrice: "$3.49" },
      { itemName: "Cinnamon Roll", itemPrice: "$3.99" },
      { itemName: "Chocolate Donut", itemPrice: "$2.49" },
      { itemName: "Cheese Danish", itemPrice: "$3.49" },
      { itemName: "Pumpkin Spice Latte", itemPrice: "$5.99" },
    ],
  },
  {
    ratings: "4.6 - 35mins",
    image: "/offers/offer3.jpg",
    title: "Burger King",
    url: "burgerking",
    items: "Family Meal Discount",
    city: "Toronto",
    listItems: [
      { itemName: "Whopper", itemPrice: "$8.99" },
      { itemName: "Chicken Royale", itemPrice: "$7.99" },
      { itemName: "Fish Sandwich", itemPrice: "$6.49" },
      { itemName: "Onion Rings", itemPrice: "$3.99" },
      { itemName: "Chicken Fries", itemPrice: "$5.99" },
      { itemName: "Double Cheeseburger", itemPrice: "$9.49" },
      { itemName: "Bacon King", itemPrice: "$10.99" },
      { itemName: "Spicy Chicken Nuggets", itemPrice: "$6.99" },
      { itemName: "Shakes", itemPrice: "$4.49" },
      { itemName: "Apple Pie", itemPrice: "$2.99" },
    ],
  },
  {
    ratings: "4.3 - 20mins",
    image: "/offers/offer4.jpg",
    title: "Domino's",
    url: "dominos",
    items: "Free Dessert with Pizza",
    city: "Seoul",
    listItems: [
      { itemName: "Pepperoni Pizza", itemPrice: "$11.99" },
      { itemName: "Vegetarian Supreme", itemPrice: "$10.99" },
      { itemName: "Hawaiian Pizza", itemPrice: "$12.49" },
      { itemName: "Chicken Alfredo Pasta", itemPrice: "$8.99" },
      { itemName: "Stuffed Cheesy Bread", itemPrice: "$6.99" },
      { itemName: "Chocolate Lava Cake", itemPrice: "$4.99" },
      { itemName: "Cinnamon Bread Twists", itemPrice: "$5.49" },
      { itemName: "Chicken Wings", itemPrice: "$7.99" },
      { itemName: "Garlic Parmesan Pizza", itemPrice: "$9.49" },
      { itemName: "BBQ Chicken Pizza", itemPrice: "$10.99" },
    ],
  },
  {
    ratings: "4.1 - 25mins",
    image: "/offers/offer5.jpg",
    title: "Subway",
    url: "subway",
    items: "Sub of the Day Special",
    city: "Barcelona",
    listItems: [
      { itemName: "Italian B.M.T.", itemPrice: "$6.99" },
      { itemName: "Spicy Italian", itemPrice: "$6.49" },
      { itemName: "Chicken Teriyaki", itemPrice: "$7.49" },
      { itemName: "Veggie Delight", itemPrice: "$5.99" },
      { itemName: "Tuna Sub", itemPrice: "$7.99" },
      { itemName: "Subway Club", itemPrice: "$6.99" },
      { itemName: "Roast Beef", itemPrice: "$8.49" },
      { itemName: "Steak and Cheese", itemPrice: "$7.99" },
      { itemName: "Buffalo Chicken", itemPrice: "$7.49" },
      { itemName: "Meatball Marinara", itemPrice: "$6.49" },
    ],
  },
  {
    ratings: "4.7 - 30mins",
    image: "/offers/offer6.jpg",
    title: "Krispy Kreme",
    url: "krispykreme",
    items: "Assorted Donut Box",
    city: "Dublin",
    listItems: [
      { itemName: "Original Glazed", itemPrice: "$1.29" },
      { itemName: "Chocolate Iced", itemPrice: "$1.49" },
      { itemName: "Strawberry Filled", itemPrice: "$1.69" },
      { itemName: "Kreme Filled", itemPrice: "$1.79" },
      { itemName: "Powdered Sugar", itemPrice: "$1.29" },
      { itemName: "Cinnamon Twist", itemPrice: "$1.59" },
      { itemName: "Maple Iced", itemPrice: "$1.49" },
      { itemName: "Blueberry Cake", itemPrice: "$1.69" },
      { itemName: "Raspberry Filled", itemPrice: "$1.79" },
      { itemName: "Lemon Kreme", itemPrice: "$1.89" },
    ],
  },
  {
    ratings: "4.4 - 32mins",
    image: "/offers/offer7.jpg",
    title: "Panda Express",
    url: "pandaexpress",
    items: "Chinese Feast Deal",
    city: "Sydney",
    listItems: [
      { itemName: "Orange Chicken", itemPrice: "$8.99" },
      { itemName: "Beijing Beef", itemPrice: "$9.49" },
      { itemName: "Kung Pao Chicken", itemPrice: "$7.99" },
      { itemName: "Honey Walnut Shrimp", itemPrice: "$10.99" },
      { itemName: "Chow Mein", itemPrice: "$5.99" },
      { itemName: "Fried Rice", itemPrice: "$4.99" },
      { itemName: "Egg Roll", itemPrice: "$2.99" },
      { itemName: "SweetFire Chicken Breast", itemPrice: "$8.49" },
      { itemName: "Teriyaki Chicken", itemPrice: "$7.99" },
      { itemName: "Mushroom Chicken", itemPrice: "$6.99" },
    ],
  },
  {
    ratings: "4.9 - 20mins",
    image: "/offers/offer8.jpg",
    title: "Tim Hortons",
    url: "timhortons",
    items: "Breakfast Combo Savings",
    city: "Vancouver",
    listItems: [
      { itemName: "Double-Double Coffee", itemPrice: "$2.99" },
      { itemName: "Maple Pecan Danish", itemPrice: "$3.49" },
      { itemName: "Bacon Breakfast Wrap", itemPrice: "$4.99" },
      { itemName: "Old Fashioned Plain Donut", itemPrice: "$1.29" },
      { itemName: "Iced Cappuccino", itemPrice: "$3.99" },
      { itemName: "Everything Bagel", itemPrice: "$2.49" },
      { itemName: "Sausage Biscuit", itemPrice: "$4.49" },
      { itemName: "French Vanilla Cappuccino", itemPrice: "$3.99" },
      { itemName: "Farmers Breakfast Sandwich", itemPrice: "$5.49" },
      { itemName: "Chill Double Chocolate Donut", itemPrice: "$1.79" },
    ],
  },
  {
    ratings: "4.8 - 22mins",
    image: "/offers/offer9.jpg",
    title: "McDonald's",
    url: "mcdonalds",
    items: "Happy Meal Discounts",
    city: "Paris",
    listItems: [
      { itemName: "Big Mac", itemPrice: "$5.99" },
      { itemName: "McNuggets", itemPrice: "$4.99" },
      { itemName: "Filet-O-Fish", itemPrice: "$6.49" },
      { itemName: "Quarter Pounder", itemPrice: "$6.99" },
      { itemName: "Happy Meal", itemPrice: "$3.99" },
      { itemName: "McFlurry", itemPrice: "$2.99" },
      { itemName: "Egg McMuffin", itemPrice: "$4.49" },
      { itemName: "Sausage McMuffin", itemPrice: "$3.99" },
      { itemName: "Apple Pie", itemPrice: "$1.49" },
      { itemName: "Mocha Frappé", itemPrice: "$4.99" },
    ],
  },
  {
    ratings: "4.6 - 25mins",
    image: "/offers/offer10.jpg",
    title: "Dunkin' Donuts",
    url: "dunkindonuts",
    items: "Coffee and Muffin Combo",
    city: "New York",
    listItems: [
      { itemName: "Original Blend Coffee", itemPrice: "$2.49" },
      { itemName: "Glazed Donut", itemPrice: "$1.29" },
      { itemName: "Chocolate Frosted Donut", itemPrice: "$1.49" },
      { itemName: "Blueberry Muffin", itemPrice: "$2.99" },
      { itemName: "Boston Kreme Donut", itemPrice: "$1.79" },
      { itemName: "Cinnamon Sugar Donut", itemPrice: "$1.49" },
      { itemName: "Vanilla Frosted Donut", itemPrice: "$1.69" },
      { itemName: "Pumpkin Muffin", itemPrice: "$2.49" },
      { itemName: "French Vanilla Latte", itemPrice: "$3.49" },
      { itemName: "Old Fashioned Donut", itemPrice: "$1.29" },
    ],
  },
];

// You can use the offerData array as needed in your application.
function getRandomItems(array, count) {
  const shuffledArray = array.sort(() => Math.random() - 0.5);
  return shuffledArray.slice(0, count);
}

// Randomly select 5 items from foodData and 5 items from offerData
const randomFoodItems = getRandomItems(foodData, 5);
const randomOfferItems = getRandomItems(offerData, 5);

// Combine the randomly selected items into a new array
const combinedRandomItems = [...randomFoodItems, ...randomOfferItems];

// Shuffle the combined array for a more random order
const shuffledCombinedItems = combinedRandomItems.sort(
  () => Math.random() - 0.5
);

export const randomData = shuffledCombinedItems;
